### ISSUE TITLE
Getting promisify error on fresh install.

### ISSUE THREAD

**Issue by sunnykgupta** [jeswin/basho#2]
Tried the following: 

```
➜  ~ npm install -g basho
/Users/sunnyrgupta/.nvm/versions/node/v6.9.1/bin/basho -> /Users/sunnyrgupta/.nvm/versions/node/v6.9.1/lib/node_modules/basho/dist/index.js
+ basho@0.0.47
added 6 packages in 7.251s
➜  ~ basho
/Users/sunnyrgupta/.nvm/versions/node/v6.9.1/lib/node_modules/basho/node_modules/basho-eval/dist/import-module.js:14
const stat = util.promisify(fs.stat);
                  ^

TypeError: util.promisify is not a function
    at Object.<anonymous> (/Users/sunnyrgupta/.nvm/versions/node/v6.9.1/lib/node_modules/basho/node_modules/basho-eval/dist/import-module.js:14:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sunnyrgupta/.nvm/versions/node/v6.9.1/lib/node_modules/basho/node_modules/basho-eval/dist/index.js:35:25)
    at Module._compile (module.js:570:32)
```

Must mention this is a fresh install and I'm using nvm.

**Comment by sunnykgupta** [comment]
I can attempt the polyfill! Let me try and get back here!

**Comment by jeswin** [comment]
The project to fix will be https://github.com/jeswin/basho-eval.
The test suite is fairly decent.

**Comment by jeswin** [comment]
Node 8 is now pretty common - closing.
